# Generated by Django 5.1.1 on 2024-12-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='date',
        ),
    ]
